#!/bin/sh

# set -x

DOTFILES_PATH=$(dirname $(realpath $0))
DOTFILES=(
    .spacemacs
    .zshrc
    .oh-my-zsh
    git/.gitignore
    .tmux.conf
)

relink_file() {
  # relink_file file/relative/to/repo path/to/some/dir
  DST="$2/$(basename $1)"
  mkdir -p $2
  if [ ! -f "$DST" ]; then
    [ -L "$DST" ] && rm $DST
    ln -s $DOTFILES_PATH/$1 $DST
  else
    echo file $DST already exists > /dev/stderr
  fi
}

unlink ~/.dotfiles && ln -s $DOTFILES_PATH ~/.dotfiles

for DOTFILE in ${DOTFILES[@]}
do
    echo configuring $DOTFILE
    relink_file $DOTFILE ~
done

case $(uname) in
    Darwin)
        echo configuring yabai and skhd
        relink_file .yabairc ~
        relink_file .skhdrc ~
        break;;
    Linux)
        echo configuring i3
        relink_file i3/config ~/.config/i3
        relink_file i3status/config ~/.config/i3status
        echo configuring bspwm, sxhkd and polybar
        relink_file bspwm/bspwmrc ~/.config/bspwm
        relink_file sxhkd/sxhkdrc ~/.config/sxhkd
        relink_file polybar/config ~/.config/polybar
        relink_file polybar/launch.sh ~/.config/polybar
        break;;
esac
