#!/bin/sh

DOTFILES_PATH=$(dirname $(realpath $0))
DOTFILES=(
    .spacemacs
    .zshrc
    .oh-my-zsh
    git/.gitignore
    .tmux.conf
)

unlink ~/.dotfiles && ln -s $DOTFILES_PATH ~/.dotfiles

for DOTFILE in ${DOTFILES[@]}
do
    echo configuring $DOTFILE
    ln -s $DOTFILES_PATH/$DOTFILE ~
done

case $(uname) in
    Darwin)
        echo configuring yabai and skhd
        ln -s $DOTFILES_PATH/.yabairc $DOTFILES_PATH/.skhdrc ~
        break;;
    Linux)
        echo configuring i3
        ln -s $DOTFILES_PATH/i3/config ~/.config/i3/config
        ln -s $DOTFILES_PATH/i3status/config ~/.config/i3status/config
        echo configuring bspwm, sxhkd and polybar
        ln -s $DOTFILES_PATH/bspwm/bspwmrc ~/.config/bspwm/bspwmrc
        ln -s $DOTFILES_PATH/sxhkd/sxhkdrc ~/.config/sxhkd/sxhkdrc
        ln -s $DOTFILES_PATH/polybar/config ~/.config/polybar/config
        ln -s $DOTFILES_PATH/polybar/launch.sh ~/.config/polybar/launch.sh
        break;;
esac
