[colors.primary]
background = '#1a1a23'
foreground = '#f2f2f3'

[colors.cursor]
text = '#1a1a23'
cursor = '#f2f2f3'

[colors.vi_mode_cursor]
text = '#1a1a23'
cursor = '#8b8fc1'

[colors.search.matches]
foreground = '#222330'
background = '#b593b7'

[colors.search.focused_match]
foreground = '#222330'
background = '#8b8fc1'

[colors.footer_bar]
foreground = '#222330'
background = '#e4e4e7'

[colors.hints.start]
foreground = '#222330'
background = '#a28fbb'

[colors.hints.end]
foreground = '#222330'
background = '#a28fbb'

[colors.selection]
text = '#afafb6'
background = '#222330'


[colors.normal]
black   = '#222330'
red     = '#fd4663'
green   = '#8b8fc1'
yellow  = '#a28fbb'
blue    = '#b593b7'
magenta = '#acafd3'
cyan    = '#bdafd0'
white   = '#f2f2f3'


[colors.bright]
black   = '#646574'
red     = '#fd4663'
green   = '#8b8fc1'
yellow  = '#a28fbb'
blue    = '#b593b7'
magenta = '#acafd3'
cyan    = '#bdafd0'
white   = '#f2f2f3'


[colors.dim]
black   = '#222330'
red     = '#fd4663'
green   = '#8b8fc1'
yellow  = '#a28fbb'
blue    = '#b593b7'
magenta = '#acafd3'
cyan    = '#bdafd0'
white   = '#f2f2f3'
