syntax on
set number relativenumber
set tabstop=2
set shiftwidth=2
set expandtab
set autoindent
set smartindent
set autoread
au CursorHold * checktime

" Autoindent
 filetype plugin indent on 

au VimEnter,BufWinEnter * syn match ErrorMsg " "

" Vim Plug - Plugin Installation
" https://github.com/junegunn/vim-plug
call plug#begin('~/.local/share/nvim/plugged')

  " https://github.com/artur-shaik/vim-javacomplete2
  Plug 'artur-shaik/vim-javacomplete2'

  " https://github.com/ctrlpvim/ctrlp.vim
  Plug 'ctrlpvim/ctrlp.vim'

  " https://github.com/Shougo/deoplete.nvim
  Plug 'Shougo/deoplete.nvim'

  " https://github.com/scrooloose/nerdtree
  Plug 'scrooloose/nerdtree'

" Initialize plugin system
call plug#end()

" ctrlp
set runtimepath^=~/.vim/bundle/ctrlp.vim
let g:ctrlp_map = '<c-p>'
let g:ctrlp_cmd = 'CtrlP'
let g:ctrlp_working_path_mode = 'ra'

" java
autocmd FileType java setlocal omnifunc=javacomplete#Complete

" deoplete
let g:deoplete#enable_at_startup = 1

" nerdtree
" auto-open if no file specified
autocmd StdinReadPre * let s:std_in=1
autocmd VimEnter * if argc() == 0 && !exists("s:std_in") | NERDTree | endif

" auto-close if alone
autocmd bufenter * if (winnr("$") == 1 && exists("b:NERDTree") && b:NERDTree.isTabTree()) | q | endif

" key mapping to toggle
map <C-e> :NERDTreeToggle<CR>
