[[language]]
name = "toml"
language-servers = [{ name = "taplo" }]
auto-format = true
roots = ["."]

[[language]]
name = "markdown"
language-servers = ["mdpls"]

[language-server.mdpls]
command = "mdpls"
# config = { markdown.preview.auto = true }

[language-server.taplo]
command = "taplo"
args = ["lsp", "stdio"]

[language-server.qmlls]
command = "qmlls6"

[[language]]
name = "ini"
file-types = ["ini", "conf", "preset"]
